# Generated by Django 3.0.8 on 2023-06-16 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название блюда')),
                ('photo', models.ImageField(null=True, upload_to='', verbose_name='Фото блюда')),
                ('total_calories', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Общая калорийность')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость блюда')),
            ],
            options={
                'verbose_name': 'Название блюда',
                'verbose_name_plural': 'Нзвание блюд',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название продукта')),
                ('product_calorie', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Калорийность продукта')),
            ],
            options={
                'verbose_name': 'Название продукта',
                'verbose_name_plural': 'Нзвание продуктов',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название заведения')),
                ('opening_time', models.TimeField(verbose_name='Время открытия')),
                ('closing_time', models.TimeField(verbose_name='Время закрытия')),
                ('photo', models.ImageField(null=True, upload_to='', verbose_name='Фото заведения')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес заведение')),
                ('avg_cost', models.FloatField(blank=True, null=True, verbose_name='Средняя стоимость')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('dishes', models.ManyToManyField(blank=True, null=True, to='places.Dish', verbose_name='Список блюд')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец заведения')),
            ],
            options={
                'verbose_name': 'Название заведения',
                'verbose_name_plural': 'Нзвание заведений',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(to='places.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
