# Generated by Django 3.0.8 on 2023-08-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20230623_0122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Название заведения', 'verbose_name_plural': 'Название заведений'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='total_calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Общая калорийность'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='avg_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Средняя стоимость'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='dishes',
            field=models.ManyToManyField(blank=True, to='places.Dish', verbose_name='Список блюд'),
        ),
    ]
