# Generated by Django 3.0.8 on 2024-01-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20230823_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='dishes',
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurants',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='places.Restaurant', verbose_name='Связаные заведения'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=256, verbose_name='Адрес заведения'),
        ),
    ]
