# Generated by Django 3.0.8 on 2024-01-17 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20240117_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='places.Restaurant', verbose_name='Связанные заведения'),
        ),
    ]
