# Generated by Django 3.0.8 on 2024-03-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20240212_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='avg_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Средняя стоимость'),
        ),
    ]
